# Generated by Django 5.0.7 on 2024-07-18 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=100)),
                ('api_url', models.URLField()),
                ('name_field', models.CharField(max_length=100)),
                ('email_field', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_field', models.CharField(blank=True, max_length=15, null=True)),
                ('country_field', models.CharField(blank=True, max_length=100, null=True)),
                ('state_field', models.CharField(blank=True, max_length=100, null=True)),
                ('city_field', models.CharField(blank=True, max_length=100, null=True)),
                ('district_field', models.CharField(blank=True, max_length=100, null=True)),
                ('program_field', models.CharField(blank=True, max_length=100, null=True)),
                ('course_field', models.CharField(blank=True, max_length=100, null=True)),
                ('source_field', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_field', models.JSONField(blank=True, null=True)),
                ('wrap_in_array', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.university')),
            ],
        ),
    ]
