# Generated by Django 5.0 on 2024-06-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_lead_city_alter_lead_course_alter_lead_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='extra_field',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
