# Generated by Django 5.0 on 2024-06-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_university_extra_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
