# Generated by Django 5.0 on 2024-07-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_lead_country_lead_district_university_country_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='phone_field',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
